version: "3.9"

services:

  db:
    image: postgres:17.2
    container_name: todo-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoList_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - todo-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todoList_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .

    image: do-tasks:v1
    container_name: todo-list

    restart: always

    ports:
      - "8080:8080"

    depends_on:
      db:
        condition: service_healthy

    environment:
      SPRING_PROFILES_ACTIVE: dev

    networks:
      - todo-net

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  todo-net:
    driver: bridge