version: "3.9"

services:
  db:
    image: postgres:17
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoList_db
    ports:
      - "5432:5432"
    networks:
      - todo-net

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    image: do-tasks:v1
    container_name: todo-list
    ports:
      - '8080:8080' # aplicação principal
    expose:
      - '8080'
      - '8081:8081'  # Actuator


    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todoList_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy

    networks:
      - todo-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  todo-net:
    driver: bridge

