spring:

  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    name: todo-list
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: false

server:
  port: ${PORT:8080}

application:
  security:
    jwt:

      secret-key: 504E635266556A586E3272357538782F413F4428472B4B6250645367566B6570
      expiration: 36000000
#      secret-key: ${JWT_SECRET}
#      expiration: ${JWT_EXPIRATION}