spring:

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/todoList_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  main:
  #  allow-circular-references: true
# 🔥 Corrigido: fora do bloco spring

application:
  security:
    jwt:
      secret-key: 504E635266556A586E3272357538782F413F4428472B4B6250645367566B6570
      expiration: 36000000

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  server:
    port: 8081  # Opcional: separar porta do Actuator