spring:
  application:
    name: todo-list

  datasource:
    url: jdbc:postgresql://localhost:5432/todoList_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  main:
  #  allow-circular-references: true

# 🔥 Corrigido: fora do bloco spring

application:
  security:
    jwt:
      secret-key: 504E635266556A586E3272357538782F413F4428472B4B6250645367566B6570
      expiration: 36000000
